import { ApiProperty, ApiPropertyOptional } from '@nestjs/swagger';
import {
  AiTool,
  AiToolCategory,
  Resource,
  ResourceCategory,
  Role,
  User,
} from '@prisma/client';

export class UserEntity {
  constructor(
    user: User & {
      authoredAiTools?: AiTool[];
      authoredAiToolCategories?: AiToolCategory[];
      authoredResources?: Resource[];
      authoredResourceCategories?: ResourceCategory[];
    },
  ) {
    this.id = user.id;
    this.email = user.email;
    this.name = user.name;
    this.role = user.role;
    this.bio = user.bio;
    this.emailVerified = user.emailVerified;
    this.profileImageUrl = user.profileImageUrl;
    this.createdAt = user.createdAt;
    this.updatedAt = user.updatedAt;
    this.authoredAiTools = user.authoredAiTools;
    this.authoredAiToolCategories = user.authoredAiToolCategories;
    this.authoredResources = user.authoredResources;
    this.authoredResourceCategories = user.authoredResourceCategories;
  }

  @ApiProperty({
    example: 'clx247gyz0000dz63yzz18etp',
    description: 'A unique cuid generated by Prisma when user is created',
  })
  id: string;

  @ApiProperty({
    example: 'johndoe@gmail.com',
  })
  email: string;

  @ApiProperty({
    example: 'John Doe',
    format: 'At least 2 characters',
  })
  name: string;

  @ApiProperty({
    example: Role.USER,
    enum: Role,
  })
  role: Role;

  @ApiPropertyOptional({
    example: 'I am a software developer',
    description: 'Information about the user',
  })
  bio?: string;

  @ApiProperty({
    example: false,
    description: "Whether this user's email has been verified",
  })
  emailVerified: boolean;

  @ApiPropertyOptional({
    example: 'https://cloudinary.com/jpeg',
    description: "URL to the user's uploaded profile image",
  })
  profileImageUrl?: string;

  @ApiProperty({
    example: '2022-01-01T00:00:00.000Z',
  })
  createdAt: Date;

  @ApiProperty({
    example: '2022-01-01T00:00:00.000Z',
  })
  updatedAt: Date;

  @ApiProperty({
    description: 'AI tools this user has uploaded',
  })
  authoredAiTools?: AiTool[];

  @ApiProperty({
    description: 'AI tool categories this user has uploaded',
  })
  authoredAiToolCategories?: AiToolCategory[];

  @ApiProperty({
    description: 'Resources this user has uploaded',
  })
  authoredResources?: Resource[];

  @ApiProperty({
    description: 'Resource categories this user has uploaded',
  })
  authoredResourceCategories?: ResourceCategory[];
}
